#pragma once

#include <cstdint>
#include <iomanip>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include "cuny_sms/domain/campus_code.hpp"
#include "cuny_sms/domain/course.hpp"
#include "cuny_sms/domain/employee_id.hpp"
#include "cuny_sms/domain/meeting_slot.hpp"
#include "cuny_sms/domain/section.hpp"

namespace cuny_sms {

// Inputs for creating a Section. Section number is generated by the factory
// per campus convention (CCNY uses 2-digit "01"; Brooklyn uses "TY1"; Hunter
// uses "01" or "01H" for honors).
struct SectionSpec {
    Course course;
    std::int16_t sectionNumber;  // 1, 2, 3, ...
    std::vector<MeetingSlot> slots;
    EmployeeId professorId;
    std::int32_t capacity;
    bool honors{false};  // Hunter uses suffix "H"
};

class SectionFactory {
public:
    SectionFactory(const SectionFactory&) = delete;
    SectionFactory& operator=(const SectionFactory&) = delete;
    SectionFactory(SectionFactory&&) = delete;
    SectionFactory& operator=(SectionFactory&&) = delete;
    virtual ~SectionFactory() = default;

    [[nodiscard]] virtual CampusCode campusCode() const noexcept = 0;

    [[nodiscard]] virtual Section createSection(SectionSpec spec) const = 0;

protected:
    SectionFactory() = default;

    static void validate(const SectionSpec& spec) {
        if (spec.sectionNumber < 1 || spec.sectionNumber > 999) {
            throw std::invalid_argument("SectionSpec: sectionNumber must be in [1, 999]");
        }
        if (spec.capacity < 1) {
            throw std::invalid_argument("SectionSpec: capacity must be positive");
        }
        if (spec.slots.empty()) {
            throw std::invalid_argument("SectionSpec: at least one MeetingSlot required");
        }
    }

    [[nodiscard]] static std::string padTwo(std::int16_t n) {
        std::ostringstream os;
        os << std::setw(2) << std::setfill('0') << n;
        return os.str();
    }
};

// CCNY: sections are "01", "02", ... — flat 2-digit.
class CcnySectionFactory final : public SectionFactory {
public:
    [[nodiscard]] CampusCode campusCode() const noexcept override { return CampusCode::CCNY; }

    [[nodiscard]] Section createSection(SectionSpec spec) const override {
        validate(spec);
        std::string sec = padTwo(spec.sectionNumber);
        return Section{spec.course.id(), std::move(sec), std::move(spec.slots), spec.professorId,
                       spec.capacity};
    }
};

// Brooklyn: sections are "TY1", "TY2", ... — "TY" prefix is local convention.
class BrooklynSectionFactory final : public SectionFactory {
public:
    [[nodiscard]] CampusCode campusCode() const noexcept override { return CampusCode::Brooklyn; }

    [[nodiscard]] Section createSection(SectionSpec spec) const override {
        validate(spec);
        std::ostringstream os;
        os << "TY" << spec.sectionNumber;
        return Section{spec.course.id(), os.str(), std::move(spec.slots), spec.professorId,
                       spec.capacity};
    }
};

// Hunter: 2-digit numeric, optional "H" suffix for honors sections.
class HunterSectionFactory final : public SectionFactory {
public:
    [[nodiscard]] CampusCode campusCode() const noexcept override { return CampusCode::Hunter; }

    [[nodiscard]] Section createSection(SectionSpec spec) const override {
        validate(spec);
        std::string sec = padTwo(spec.sectionNumber);
        if (spec.honors) {
            sec.push_back('H');
        }
        return Section{spec.course.id(), std::move(sec), std::move(spec.slots), spec.professorId,
                       spec.capacity};
    }
};

}  // namespace cuny_sms
